name: Build

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Lavalink-Config-Server
        run: ./gradlew build

      - name: Upload Lavalink-Config-Server.jar
        uses: actions/upload-artifact@v4
        with:
          name: Lavalink-Config-Server.jar
          path: build/libs/Lavalink-Config-Server.jar

  build-docker:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu
            dockerfile: docker/Dockerfile
            suffix: ''
            platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          - name: Alpine
            dockerfile: docker/alpine.Dockerfile
            suffix: '-alpine'
            platforms: linux/amd64,linux/arm64/v8
          - name: Distroless
            dockerfile: docker/distroless.Dockerfile
            suffix: '-distroless'
            platforms: linux/amd64,linux/arm64/v8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Lavalink-Config-Server.jar
        uses: actions/download-artifact@v4
        with:
          name: Lavalink-Config-Server.jar
          path: build/libs/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta ${{ matrix.name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            suffix=${{ matrix.suffix }},onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=

      - name: Docker Build ${{ matrix.name }} and Push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
